name: Deploy to Replicate

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Cog
      uses: replicate/setup-cog@v1
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}
    
    - name: Validate and Build
      run: |
        cog build --progress=plain
    
    - name: Push to Replicate
      run: |
        cog push r8.im/jpjpkimjp/tinos-generator --yes